# Generated by Django 3.2 on 2021-04-29 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belt_exam_app', '0002_trip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='desc',
            new_name='plan',
        ),
    ]
